### ISSUE TITLE
Mainnet pool SOL_USDC always returning "Attempt to debit an account but found no record of a prior credit."

### ISSUE THREAD

**Issue by SleepyDeb** [raydium-io/sdk_demo#9]
Hello,

I'm trying to swap SOL to USDC and viceversa; so I planned to use the swap API, 
first I tested the API with the RAY_USDC pool and it worked, than I tried to switch to SOL_USDC pool and this is the program output:
```
bash
npm run start

> raydium-sdk-demo@1.0.0 start
> ts-node src/demo_mainnet.ts

Cf7BQUbeCgV6xmecU2P4b5bMGQEVQbQjkhCQAJFQdZbm
swap start
swap: 58oQChx4yWmvKdwLLZzBi4ChoCc2fqCUWBkwMihLYQo2, amountIn: 0.020000000, amountOut: 0.984306, executionPrice: 49.338647
C:\dev\personal\sdk_demo\node_modules\@solana\web3.js\src\connection.ts:4243
      throw new SendTransactionError(
            ^
    at Connection.sendEncodedTransaction (C:\dev\personal\sdk_demo\node_modules\@solana\web3.js\src\connection.ts:4243:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (C:\dev\personal\sdk_demo\node_modules\@solana\web3.js\src\connection.ts:4205:20)
    at async Connection.sendTransaction (C:\dev\personal\sdk_demo\node_modules\@solana\web3.js\src\connection.ts:4193:12)
    at async swap (C:\dev\personal\sdk_demo\src\util.ts:72:16)
    at async C:\dev\personal\sdk_demo\src\demo_mainnet.ts:37:5 {
  logs: []
}
```

this is my `util.ts` file version, I just exposed the value in the parameters and changed the preflight to false to expose the errors: 
```typescript

export async function swap(connection: Connection, poolKeys: LiquidityPoolKeys, ownerKeypair: Keypair, tokenAccounts: TokenAccount[], value: number){
  console.log('swap start')

  const owner = ownerKeypair.publicKey
  const poolInfo = await Liquidity.fetchInfo({connection, poolKeys})

  // real amount = 1000000 / 10**poolInfo.baseDecimals
  const amountIn = new TokenAmount(new Token(poolKeys.baseMint, poolInfo.baseDecimals), value, false)

  const currencyOut = new Token(poolKeys.quoteMint, poolInfo.quoteDecimals)

  // 5% slippage
  const slippage = new Percent(5, 100)

  const {
    amountOut,
    minAmountOut,
    currentPrice,
    executionPrice,
    priceImpact,
    fee,
  } = Liquidity.computeAmountOut({ poolKeys, poolInfo, amountIn, currencyOut, slippage, })

  
  // @ts-ignore
  // console.log(amountOut.toFixed(), minAmountOut.toFixed(), currentPrice.toFixed(), executionPrice.toFixed(), priceImpact.toFixed(), fee.toFixed())
  console.log(`swap: ${poolKeys.id.toBase58()}, amountIn: ${amountIn.toFixed()}, amountOut: ${amountOut.toFixed()}, executionPrice: ${executionPrice.toFixed()}`,)
  
  // const minAmountOut = new TokenAmount(new Token(poolKeys.quoteMint, poolInfo.quoteDecimals), 1000000)
  
  const {transaction, signers} = await Liquidity.makeSwapTransaction({
      connection,
      poolKeys,
      userKeys: {
          tokenAccounts,
          owner,
      },
      amountIn,
      amountOut: minAmountOut,
      fixedSide: "in"
  })

  const txid = await connection.sendTransaction(
      transaction, 
      [...signers, ownerKeypair],
      { skipPreflight: false }
  );

  console.log(`https://explorer.solana.com/tx/${txid}`)
  console.log('swap end')
}
```

This is my `demo_mainnet.ts` where I swapped the RAY_USDC pool for SOL_USDC one:
```typescript

(async () => {
    const connection = new Connection("https://solana-api.projectserum.com", "confirmed");

    // const secretKey = bs58.decode('3qswEeCJcA9ogpN3JEuXBtmnU35YPzSxBwzrk6sdTPhogMJ64WuabU9XWg2yUegJvv1qupYPqo2jQrrK26N7HGsD')
    const secretKey = Buffer.from("....", 'hex');
    const ownerKeypair = Keypair.fromSecretKey( secretKey )
    const owner = ownerKeypair.publicKey;
    console.log(owner.toString());

    const tokenAccounts = await getTokenAccountsByOwner(connection, owner)

    const FIDA_RAY = "2dRNngAm729NzLbb1pzgHtfHvPqR4XHFmFyYK78EfEeX"
    const RAY_USDC = "6UmmUiYoBjSrhakAobJw8BvkmJtDVxaeBtbt7rxWo1mg"
    const SOL_USDC = "58oQChx4yWmvKdwLLZzBi4ChoCc2fqCUWBkwMihLYQo2"
    // const allPoolKeys = await fetchAllPoolKeys(connection);
    // const poolKeys = allPoolKeys.find((item) => item.id.toBase58() === RAY_USDC)

    const fromPoolKeys = await fetchPoolKeys(connection, new PublicKey(FIDA_RAY))
    const poolKeys = await fetchPoolKeys(connection, new PublicKey(SOL_USDC))
    const FIDA_MINT_ID = fromPoolKeys.baseMint;
    const USDC_MINT_ID = poolKeys.quoteMint;
    const relatedPoolKeys = await getRouteRelated(connection, FIDA_MINT_ID, USDC_MINT_ID)

    await swap(connection, poolKeys, ownerKeypair, tokenAccounts, 0.02)
})()
```

Do you have any idea? This is my wallet pubkey: Cf7BQUbeCgV6xmecU2P4b5bMGQEVQbQjkhCQAJFQdZbm
I'm a newbie of blockchain programming, is 1 week that I'm trying to make it work but i'm stucked...
thanks in advance for your time

**Comment by firememory** [comment]
fixed , plz retry

**Comment by SleepyDeb** [comment]
> fixed , plz retry

Hey, thanks a lot, I would not be able to try until tomorrow..

could u help me understand what was broken?

Thanks again
